name: Loft CLI Install
author: loft.sh
description: Installs the loft CLI
inputs:
  version:
    description: 'The version of loft to install'
    required: false
    default: 'latest'
  url:
    description: 'The Loft URL'
    required: true
  access-key:
    description: 'The Loft Access Key'
    required: true
  insecure:
    description: 'Allow login into an insecure loft instance (default false)'
    required: false
    default: 'false'
  docker-login:
    description: 'If true, will log into the docker image registries the user has image pull secrets for (default true)'
    required: false
    default: 'true'
  kubectl-install:
    description: 'Install kubectl if not already installed'
    required: false
    default: 'true'
  kubectl-version:
    description: 'The version of the kubectl to install'
    required: false
    default: 'latest'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
