name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    env:
      ACTIONS_STEP_DEBUG: true
    strategy:
      matrix:
        os:
          - windows-latest
          - windows-2022
          - windows-2019
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-18.04
          # - ubuntu-16.04
          - macos-latest
          - macos-11
          - macos-10.15
        version:
          - v5.14.0
          - 5.14.0
          - latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: ${{ matrix.version }}
          loft-url: ${{ secrets.LOFT_URL }}
          loft-access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - run: loft --version
      # - run: loft vars username
